yarnPath: .yarn/releases/yarn-3.5.1.cjs

packageExtensions:
  # for react
  styled-components@*:
    dependencies:
      react-is: "*"
  gatsby@*:
    dependencies:
      babel-plugin-styled-components: "*"

  # for testing
  jest-environment-puppeteer@*:
    dependencies:
      puppeteer-core: "*"
