services:
  api:
    image: hungluu/fm-api-dev
    build:
      context: api
      target: fm-api-dev
    environment:
      SKIP_DB_SETUP: "true"
    env_file:
      - .env
    volumes:
      - ${MOUNT_VOLUME:-./api:/app:delegated}
    ports:
      - 3000:3000
    depends_on:
      - db
      - cache
      - jobs
    networks:
      - pub-net
      - priv-net

  jobs:
    image: hungluu/fm-api-dev
    build:
      context: api
      target: fm-api-dev
    command: bundle exec sidekiq
    environment:
      SKIP_DB_SETUP: "true"
    env_file:
      - .env
    volumes:
      - ${MOUNT_VOLUME:-./api:/app:ro}
    depends_on:
      - db
      - cache
    networks:
      - priv-net

  db:
    image: bitnami/postgresql:15
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRESQL_DATABASE: "${POSTGRESQL_DATABASE}"
    volumes:
      - db_data:/bitnami/postgresql
    networks:
      - priv-net

  cache:
    image: bitnami/redis:6.2
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - priv-net

volumes:
  db_data:


networks:
  priv-net:
    internal: true
  pub-net:
