services:
  # A Docker web service
  - type: web
    name: api
    region: singapore
    env: docker
    rootDir: api
    healthCheckPath: /health
    envVars:
      - key: POSTGRES_HOST
        fromDatabase:
          name: db
          property: host
      - key: POSTGRES_USER
        fromDatabase:
          name: db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: db
          property: password
      - key: POSTGRES_DATABASE
        fromDatabase:
          name: db
          property: database
      - key: REDIS_URL
        fromService:
          type: redis
          name: cache
          property: connectionString
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: API_SECRET
        generateValue: true
      - key: SECRET_KEY_BASE
        generateValue: true
  - type: redis
    name: cache
    region: singapore
    ipAllowList: [] # only allow internal connections

databases:
  - name: db
    databaseName: apidb
    region: singapore
