name: "e2e"
on:
  workflow_dispatch:

jobs:
  e2e_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Copy env
        run: echo "${{ secrets.TEST_ENV }}" > .env
      - name: Setup Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: make ui_local_init_ci
      - name: Build api
        run: make api_local_build
      - name: Test e2e
        run: make e2e_test_ci
      - name: Clean resources
        run: make api_local_clean
